<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-29T23:35:21 IST" name="Suite" finished-at="2023-06-29T23:40:33 IST" duration-ms="311256">
    <groups>
    </groups>
    <test started-at="2023-06-29T23:35:21 IST" name="Test" finished-at="2023-06-29T23:40:33 IST" duration-ms="311256">
      <class name="test.LoginTest">
        <test-method is-config="true" signature="initialize()[pri:0, instance:test.LoginTest@5ef5c734]" started-at="2023-06-29T23:35:22 IST" name="initialize" finished-at="2023-06-29T23:35:59 IST" duration-ms="37270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="LoginTestCases(java.lang.String)[pri:0, instance:test.LoginTest@5ef5c734]" started-at="2023-06-29T23:36:01 IST" name="LoginTestCases" data-provider="DocFileRead" finished-at="2023-06-29T23:37:11 IST" duration-ms="70186" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestCases -->
        <test-method signature="LogoutTestCase()[pri:1, instance:test.LoginTest@5ef5c734]" started-at="2023-06-29T23:37:11 IST" name="LogoutTestCase" finished-at="2023-06-29T23:37:14 IST" duration-ms="2996" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutTestCase -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:test.LoginTest@5ef5c734]" started-at="2023-06-29T23:37:14 IST" name="Teardown" finished-at="2023-06-29T23:37:17 IST" duration-ms="2302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- test.LoginTest -->
      <class name="test.CreateCollectorTest">
        <test-method is-config="true" signature="initialize()[pri:0, instance:test.CreateCollectorTest@481ba2cf]" started-at="2023-06-29T23:37:17 IST" name="initialize" finished-at="2023-06-29T23:37:45 IST" duration-ms="28136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="CreationCases(java.lang.String)[pri:0, instance:test.CreateCollectorTest@481ba2cf]" started-at="2023-06-29T23:37:45 IST" name="CreationCases" description="verifying login page title test" finished-at="2023-06-29T23:37:45 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot inject @Test annotated Method [CreationCases] with [class java.lang.String].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [CreationCases] with [class java.lang.String].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:436)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:350)
at org.testng.internal.Parameters.createParameters(Parameters.java:693)
at org.testng.internal.Parameters.handleParameters(Parameters.java:879)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreationCases -->
        <test-method signature="CreateCollectortTestCases(java.lang.String)[pri:1, instance:test.CreateCollectorTest@481ba2cf]" started-at="2023-06-29T23:37:50 IST" name="CreateCollectortTestCases" data-provider="DocFileReadFormCreation" finished-at="2023-06-29T23:40:09 IST" duration-ms="138322" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.CreateCollectorTest.CreateCollectortTestCases(CreateCollectorTest.java:136)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCollectortTestCases -->
        <test-method signature="LogoutTestCase()[pri:2, instance:test.CreateCollectorTest@481ba2cf]" started-at="2023-06-29T23:40:10 IST" name="LogoutTestCase" finished-at="2023-06-29T23:40:31 IST" duration-ms="21320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutTestCase -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:test.CreateCollectorTest@481ba2cf]" started-at="2023-06-29T23:40:31 IST" name="Teardown" finished-at="2023-06-29T23:40:33 IST" duration-ms="1656" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- test.CreateCollectorTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
